### ISSUE TITLE
Instructions in README.md on how to run the test suite

### ISSUE THREAD

**Issue by betelgeuse** [andywer/drag-mock#4]
It's not immediately clear how to run the test suite for the project. It would be helpful for contributors to have a section in README.md with the commands to run the suite.

**Comment by andywer** [comment]
Just wrote this: https://github.com/andywer/drag-mock/blob/develop/README.md#development

**Comment by betelgeuse** [comment]
@andywer  looks reasonable

**Comment by andywer** [comment]
Thank you!
