### ISSUE TITLE
Expected first parameter to be a targetElement

### ISSUE THREAD

**Issue by jaqua** [andywer/drag-mock#9]
I want to move an element to a specific position. Therefore I'm using `webdriver.io` and `drag-mock`.

This is what I come up with. But I get the error `Error: Expected first parameter to be a targetElement. Instead got: #canvas g.element`

	import dragMock from 'drag-mock';

	describe('Test', () => {
		before('setup', (done) => {
			dragMock.extendWebdriver(browser);
			dragMock.loadLibrary(browser);
		});

		describe('element', () => {
			it('should be moved', (done) => {
				dragMock
					.dragStart('#canvas g.element')
					.drop('#canvas', { clientX: 10, clientY: 10 });

				done();
			});
		});
	});

**Comment by andywer** [comment]
Hey @jaqua. It's supposed to be `webdriver.dragStart()`, not `dragMock.dragStart()` if you use the webdriver integration.

But there seems to be a problem with newer webdriver versions (see #8). Using an older webdriver might work for now.
